### ISSUE TITLE
possible bug in spreadFire ?

### ISSUE THREAD

**Issue by tobozo** [x1sec/game-and-watch-doom-fire#1]
Hey and thanks for this great project, I had a lot of fun [porting this to esp32](https://www.youtube.com/watch?v=Kb8k513iJjk).

Spotted this code in `spreadFire()`: 

    firePixels[from - fireWidth] = 0;

On ESP32 this crashes when the value of `from` is zero (produces a negative index in firePixels array).

Maybe the STM32 doesn't care about negative indexes or silently rotates them, but here's what I came up with to fix that crash (spoil: loops start at 1 instead of 0):

```C
void doFire() {
  for (int x = 1; x < FIRE_WIDTH; x++) {
    for (int y = 1; y < FIRE_HEIGHT; y++) {
      spreadFire(y * FIRE_WIDTH + x);
      uint16_t intensity = firePixels[x + y * FIRE_WIDTH];
      rect( x*pixel_sz, y*pixel_sz, pixel_sz, pixel_sz, palette[intensity] );
    }
  }
}
```

thanks again for the fun !

**Comment by x1sec** [comment]
Good catch! Added your change.
